# fly.toml app configuration file generated for ssafy-2024-backend-seoul2-test on 2024-12-31T14:55:54+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stmgenie'
primary_region = 'nrt'

[build]
builder = "paketo-buildpacks/builder:base"

[env]
PORT = '8000'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
